name: mpv-assignments-cpu-only
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cpuonly=1.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.9.1
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2020.0
  - ipykernel=5.2.1
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.17
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - ninja=1.9.0
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1f
  - pandoc=2.9.2.1
  - parso=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyrsistent=0.16.0
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.4.0
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - testpath=0.4.4
  - tk=8.6.8
  - torchvision=0.5.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - cachetools==4.1.0
    - chardet==3.0.4
    - cycler==0.10.0
    - google-auth==1.14.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.28.1
    - idna==2.9
    - ipython-genutils==0.2.0
    - kiwisolver==1.2.0
    - kornia==0.2.1
    - markdown==3.2.1
    - matplotlib==3.2.1
    - oauthlib==3.1.0
    - opencv-contrib-python==4.2.0.34
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - pytz==2019.3
    - pyzmq==19.0.0
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scipy==1.4.1
    - seaborn==0.10.0
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorboardx==2.0
    - terminado==0.8.3
    - tqdm==4.45.0
    - urllib3==1.25.9
    - webencodings==0.5.1
    - werkzeug==1.0.1

